server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
          - Path=/products/**

        - id: order-service
          uri: http://localhost:8082
          predicates:
          - Path=/orders/**

        # Rutas para Swagger del Product Service
        - id: product-swagger-ui
          uri: http://localhost:8081
          predicates:
            - Path=/products/swagger-ui/**
          filters:
            - RewritePath=/products/swagger-ui/(.*), /swagger-ui/$1

           # Rutas para Swagger del Order Service
        - id: order-swagger-ui
          uri: http://localhost:8082
          predicates:
            - Path=/orders/swagger-ui/**
          filters:
            - RewritePath=/orders/swagger-ui/(.*), /swagger-ui/$1

logging:
  level:
    org.springframework: DEBUG