server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          predicates:
            - Path=/orders/**
          uri: http://localhost:8082
        - id: products-service
          predicates:
            - Path=/products/**
          uri: http://localhost:8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    urls:
     - name: products-service
       url: /products/api-docs
     - name: order-service
       url: /orders/api-docs





logging:
  level:
    org.springframework: DEBUG