server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: order-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: Post*124*
  flyway:
      url: jdbc:postgresql://localhost:5432/orderdb
      user: postgres
      password: Post*124*

springdoc:
  api-docs:
    enabled: true
    path: /orders/api-docs
  swagger-ui:
    enabled: true
    path: /orders/swagger-ui/index.html

