server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/productdb
    username: postgres
    password: Post*124*
  flyway:
      url: jdbc:postgresql://localhost:5432/productdb
      user: postgres
      password: Post*124*

springdoc:
  api-docs:
    path: /products/api-docs
  swagger-ui:
    path: /products/swagger-ui/index.html
